# This workflow updates the table of OpenMDAO POEMs in the README.md with each push

name: POEM Linter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run script
      run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          $status = 0
          for added_modified_file in "${added_modified_files[@]}"; do
            python ./.github/scripts/linter.py '${added_modified_file}'"
            $status = $status | $?
          done
          if [ $status -eq 0 ]
          then
            echo "Linting successful"
            exit 0
          else
            echo "Linting error"
            exit 1
          fi
